version: '3.9'
services:
  src:
    image: postgres:11
    ports:
      - 5433:5432
    volumes:
      - ./src/init.sh:/docker-entrypoint-initdb.d/initdb.sh
    environment:
      - PGPASSWORD=src
      - POSTGRES_PASSWORD=database
      - POSTGRES_USER=database
    command: ["postgres", "-c", "wal_level=logical"]

  dest:
    image: postgres:11
    ports:
      - 5434:5432
    environment:
      - PGPASSWORD=dest
      - POSTGRES_PASSWORD=database
      - POSTGRES_USER=database
    command: ["postgres", "-c", "wal_level=logical"]

  traffic:
    image: mhoush/psycopg2
    ports:
      - 8080:80
    volumes:
      - ./traffic/main.py:/src/main.py
    working_dir: /src/
    command: ["python", "main.py"]
    tty: true
    depends_on:
      - src
      - dest
