version: '3.9'
services:
  src:
    image: postgres:11
    ports:
      - 5433:5432
    volumes:
      - ./src/init.sh:/docker-entrypoint-initdb.d/initdb.sh
    environment:
      - PGPASSWORD=src
      - POSTGRES_PASSWORD=src
      - POSTGRES_USER=src

  dest:
    image: postgres:11
    ports:
      - 5434:5432
    environment:
      - PGPASSWORD=dest
      - POSTGRES_PASSWORD=dest
      - POSTGRES_USER=dest

  traffic:
    image: mhoush/psycopg2
    volumes:
      - ./traffic/main.py:/src/main.py
    working_dir: /src/
    command: ["python", "main.py"]
    depends_on:
      - src
